name: BlockRegen
main: nl.aurorion.blockregen.BlockRegen
version: ${project.version}
authors: [ Aurorion, Wertik1206 ]
softdepend: [ Mutliverse-Core, Residence, Vault, WorldEdit, Towny, Jobs, GriefPrevention, PlaceholderAPI, WorldGuard ]
api-version: "1.13"
commands:
  blockregen:
    aliases: [ br, bregen, blockr, breg, brg ]
    description: Main plugin command
permissions:
  blockregen.command:
    default: false
  blockregen.command.*:
    default: false
  blockregen.command.reload:
    default: false
    description: Allow the use of reload command and its subcommands
  blockregen.command.bypass:
    default: false
    description: Allow the use of bypass command and its subcommands
  blockregen.command.check:
    default: false
    description: Allow the use of check command and its subcommands
  blockregen.command.tools:
    default: false
    description: Allow the use of tools command and its subcommands
  blockregen.command.regions:
    default: false
    description: Allow the use of regions command and its subcommands
  blockregen.command.regen:
    default: false
    description: Allow the use of regen command and its subcommands
  blockregen.command.debug:
    default: false
    description: Allow the use of debug command and its subcommands
  blockregen.command.discord:
    default: false
    description: Allow the use of discord command and its subcommands
  blockregen.command.events:
    default: false
    description: Allow the use of events command and its subcommands
  blockregen.block.*:
    default: true
    description: Gives player the ability to mine ores
  blockregen.select:
    description: Allows player to select locations for regions
  blockregen.region:
    description: Allows player to select presets for regions